
---

- name: "synchronize backend files"
  synchronize:
    src: ../../backend
    dest: /home/ubuntu
    recursive: true

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    pm2 start npm -- run "start:dev"