
---

- name: Copy a "sudoers" file on the remote machine for editing
  copy:
    src: backend/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: yes 

- name: Executing node
  shell: |
    cd /home/ubuntu
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start