
---

- name: Copy a "sudoers" file on the remote machine for editing
  copy:
    src: 'files/artifact.tar.gz'
    dest: '/home/ubuntu'

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  apt:
    name: nodejs
    state: present

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: Executing node
  shell: |
    cd /home/ubuntu
    npm i tar.gz
    tar -xzvf my.tar.gz .
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start