
---
- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: ./

- name: Executing node
  shell: |
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start