
---

- name: "Installing Rsync"
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
  with_items:
  - rsync
  
- name: Copy a "sudoers" file on the remote machine for editing
  copy:
    src: ../../../../artifact.tar.gz
    dest: /home/ubuntu
    remote_src: yes 

- name: Executing node
  shell: |
    cd /home/ubuntu
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start